leftnav:
- identifier: 2194fd7c-6438-3372-4400-e0ff6cc66e2c
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-04803e597d5a4204b53e7d0858e3f43a
  name: 2.009 PRODUCT ENGINEERING PROCESS
  url: https://web.mit.edu/2.009/www/index.html
  weight: 1000
- identifier: external-bd308da4fe6a4e148af07103e239bb2c
  name: 2.S009 EXPLORATIONS IN PRODUCT DESIGN
  url: https://2s009.com/
  weight: 1010
